/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'MarkPerry' at '26/12/14 8:32 PM' with Gradle 2.2.1
 *
 * @author MarkPerry, @date 26/12/14 8:32 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
